{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inference-api.fullname" . }}-secret
  labels:
    {{- include "inference-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end -}}
